Updated README and added LICENSE
AEGEE/oms-neo-core pull request #42
Opened 2017-07-17 17:05 UTC by i3anaan

2017-07-17 17:06 UTC, i3anaan commented
Additionally, I have updated the installation instructions on Confluence:
https://oms-project.atlassian.net/wiki/spaces/GENERAL/pages/17235970/Installation

2017-07-25 12:34 UTC, linuxbandit requested changes
It's ok except the 2 inconsistencies/typo

2017-07-25 12:34 UTC, linuxbandit commented on README.md
> +The core service repository for the [Online Management System (OMS)](https://github.com/AEGEE/oms-docker), an open-source project of student association [AEGEE-Europe](http://aegee.org/).
online management system?

2017-07-25 12:34 UTC, linuxbandit commented on README.md
> +OMS-core Is build upon Laravel, a PHP framework.
built*

2017-07-25 12:44 UTC, i3anaan commented on README.md
> +The core service repository for the [Online Management System (OMS)](https://github.com/AEGEE/oms-docker), an open-source project of student association [AEGEE-Europe](http://aegee.org/).
Whoops. Fun fact: this is copied from the README in OMS-Docker, so you missed it there :D

2017-07-25 13:08 UTC, merged